image:
    file: .gitpod.Dockerfile

ports:
    - port: 8888
      onOpen: open-browser

tasks:
    - before: |
          mkdir -p /workspace/.caches/pre-commit
          ln -s /workspace/.caches/pre-commit  ~/.cache/pre-commit
      init: |
          #   cd $GITPOD_REPO_ROOT/cpputil/unstructured
          #   mkdir -p build && cd build && cmake ..
          #   ln -s $(pwd)/compile_commands.json $GITPOD_REPO_ROOT/cpputil/unstructured
            cd $GITPOD_REPO_ROOT
            ./scripts/init_env.sh -i
            # cd /workspace && git clone https://github.com/GridTools/atlas4py.git && pip install -e atlas4py
            PYENV_PYTHON_VERSION=$(python --version | cut -d ' ' -f 2)
            cp ~/.pyenv/versions/${PYENV_PYTHON_VERSION}/lib/python${PYENV_PYTHON_VERSION:0:3}/site-packages/easy-install.pth /workspace/.pip-modules/lib/python${PYENV_PYTHON_VERSION:0:3}/site-packages/
            cp ~/.pyenv/versions/${PYENV_PYTHON_VERSION}/lib/python${PYENV_PYTHON_VERSION:0:3}/site-packages/*.egg-link /workspace/.pip-modules/lib/python${PYENV_PYTHON_VERSION:0:3}/site-packages/
            cd $GITPOD_REPO_ROOT
            # pre-commit install --install-hooks
            # gp preview file://$GITPOD_REPO_ROOT/docs/_build/html/index.html
      command: |
          ln -s $GITPOD_REPO_ROOT/.jupyter ~/
          jupyter-lab --notebook-dir=$GITPOD_REPO_ROOT/examples/workshop --NotebookApp.allow_origin=\'$(gp url 8888)\'

github:
    prebuilds:
        # enable for the master/default branch (defaults to true)
        master: true
        # enable for all branches in this repo (defaults to false)
        branches: true
        # enable for pull requests coming from this repo (defaults to true)
        pullRequests: true
        # enable for pull requests coming from forks (defaults to false)
        pullRequestsFromForks: true
        # add a check to pull requests (defaults to true)
        addCheck: true
        # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
        addComment: false
        # add a "Review in Gitpod" button to the pull request's description (defaults to false)
        addBadge: false
        # add a label once the prebuild is ready to pull requests (defaults to false)
        addLabel: false

vscode:
    extensions:
        - hbenl.vscode-test-explorer@2.18.0:vdCRJ/Ymtg3XxeNBz8PyMA==
        - littlefoxteam.vscode-python-test-adapter@0.4.2:XMMyP3hKqOIsEsP2ZJHrVQ==
        # - ms-vscode.cmake-tools@1.4.1:SXfYiUwB07188Cqeu95dhg==
        # - twxs.cmake@0.0.17:9s7m9CWOr6i6NZ7CNNF4kw==
