image:
    file: .gitpod.Dockerfile

tasks:
    - before: |
          mkdir -p /workspace/.caches/pre-commit
          ln -s /workspace/.caches/pre-commit  ~/.cache/pre-commit
          cd $GITPOD_REPO_ROOT
          ./scripts/init_env.sh -i
      init: |
          pre-commit install --install-hooks
          gp preview file://$GITPOD_REPO_ROOT/docs/_build/html/index.html
