tasks:
    - before: |
          mkdir -p /workspace/.caches/pre-commit
          ln -s /workspace/.caches/pre-commit  ~/.cache/pre-commit
          alias pre-commit="PIP_USER=no pre-commit"
          cd /workspace/eve
      init: |
          ./scripts/init_env.sh -i
          pre-commit install
      command: |
          gp preview file:///workspace/eve/docs/_build/html/index.html
