tasks:
    - before: |
          cd /workspace/eve
          alias pre-commit="PIP_USER=no pre-commit"
      init: |
          ./scripts/init_env.sh -i
          pre-commit install
      command: |
          gp preview file:///workspace/eve/docs/_build/html/index.html
