repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
    -   id: fix-encoding-pragma
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.1
    hooks:
    -   id: flake8
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.761
#     hooks:
#     -   id: mypy
#         exclude: ^install-local.py$
