repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
          - id: check-json
          - id: check-toml
          - id: check-yaml
          - id: fix-encoding-pragma

    - repo: https://github.com/asottile/seed-isort-config
      rev: v1.9.3
      hooks:
          - id: seed-isort-config
            args: [--application-directories=src]

    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.21
      hooks:
          - id: isort

    - repo: https://github.com/psf/black
      rev: 19.10b0
      hooks:
          - id: black

    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.9
      hooks:
          - id: flake8
            additional_dependencies:
                [darglint, flake8-bugbear, flake8-builtins, flake8-docstrings]
#
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.761
#     hooks:
#     -   id: mypy
#         exclude: ^install-local.py$
#         additional_dependencies: [pydantic~=1.0]
