name: gh-pages

on:
    push:
        branches:
            - gh-pages-deploy

jobs:
    build:
        runs-on: ubuntu-latest
        container: mrtravis/gridtools:gcc-9-atlas
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
              with:
                persist-credentials: false
            - name: Install github-pages-deploy-action dependencies
              run: apt-get update && apt-get install -y rsync
            - name: Install eve and dependencies
              run: |
                  python3 -m pip install .
                  python3 -m pip install -r requirements_dev.txt # TODO remove (once we don't include debugtools)
            - name: Build eve documentation
              run: |
                cd docs/eve
                make html
            - name: Build gtc documentation
              run: |
                cd docs/gtc
                make html
            - name: Build gtc_frontend documentation
              run: |
                cd docs/gt_frontend
                make html
            - name: Gather html documentation
              run: |
                mkdir _deploy
                cd _deploy
                mv ../docs/eve/_build/html/ eve
                mv ../docs/gtc/_build/html/ gtc
                mv ../docs/gt_frontend/_build/html/ gt_frontend
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@3.6.2
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                BRANCH: gh-pages # The branch the action should deploy to.
                FOLDER: _deploy # The folder the action should deploy.
                TARGET_FOLDER: docs
                CLEAN: true # Automatically remove deleted files from the deploy branch
